### ISSUE TITLE
"bpbot.utils" could not be resolved 

### ISSUE THREAD

**Issue by gplminhduc147** [xinyiz0931/tangle#1]
Hi,
I've just downloaded your project and got this error:
**Import "bpbot.utils" could not be resolved** in utils.py and validation.py files.

Ps: I've already install all the tool in Requirements.txt, I also use Python 3.7, CUDA 11.1 and PyTorch 1.8.1 just like you.

**Comment by gplminhduc147** [comment]
The problem has been solved, for anyone who gets this error like me:
1/ Install GIT
2/ Read the "Readme.md" and follow the steps.

**Comment by xinyiz0931** [comment]
Thank you for the comment! 
I just updated this repo. 
In the old version, you have to install my other repo `bpbot`. 
But in the newest version, the whole repo `tangle` is independent. You can follow README.md to install and test.
