### ISSUE TITLE
Data for training

### ISSUE THREAD

**Issue by gplminhduc147** [xinyiz0931/tangle#2]
Hello, I've run your code but there is no dataset to train. How can I get the PickDataset and PullDataset ?

**Comment by xinyiz0931** [comment]
Hi, I have updated the repo and provided the download link for the [datasets](https://github.com/xinyiz0931/tangle/blob/master/data/README.md) and [test checkpoints](https://github.com/xinyiz0931/tangle/blob/master/checkpoints/README.md). 
Please check the newest repo and make sure you pull all modifications.
