### ISSUE TITLE
What is "eNerate" command?

### ISSUE THREAD

**Issue by DucNguyenAIML** [xinyiz0931/tangle#3]
Hi, in gen_data.py there are some "eNerate" function. However, my vscode cannot identify this function.
I've already clone the bpbot and install all things in the requirement.txt file.
I will appreciate if you can show me the solution. Thank you so much

**Comment by DucNguyenAIML** [comment]
I've explored and fixed all "error typing" in **gen_data.py**:
eNerate -> enumerate
AUG_SEQ -> seq

My comment was write in June, 23rd 2024. So maybe the owner will have an update later.

**Comment by xinyiz0931** [comment]
Thank you for the comments! Yes they are actually typos...
I just updated this repository and provided testing code. 
In the newest version, I have removed `tools/gen_data.py` since it is no longer needed.
